parameters:
- name: 'folder'
  type: string
- name: 'clientsecret'
  type: string

jobs:
  - deployment:
    #displayName: DEV 
    #environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: terraform_artifacts

            - script: |
                  echo "Deploy to Move to directory"
                  ls $(Pipeline.Workspace)/terraform_artifacts/${{ parameters.folder }}
                  cd $(Pipeline.Workspace)/terraform_artifacts/${{ parameters.folder }}
                  SET ARM_CLIENT_ID=da7ad657-b2e3-4769-a1af-cc221eb0dc21
                  SET ARM_CLIENT_SECRET=${{ parameters.clientSecret }}
                  SET ARM_SUBSCRIPTION_ID=db371aa4-50d0-45d5-866b-3638e8a8e53d
                  SET ARM_TENANT_ID=3026ab1c-66a5-46df-83be-7b183a607557
                  terragrunt init --terragrunt-config ./terragrunt.dev.hcl
                  terragrunt plan --terragrunt-config ./terragrunt.dev.hcl
                  terragrunt apply --terragrunt-config ./terragrunt.dev.hcl -auto-approve